# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0002_add_step_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='ui_template',
            field=models.CharField(
                blank=True,
                default='content',
                help_text="UIKitML template name for this step (e.g., 'content', 'showcase')",
                max_length=100,
                null=True
            ),
        ),
    ]
