# Generated by Django 5.0.14 on 2026-01-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0003_step_ui_template'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='publishedmodule',
            name='unique_published_version',
        ),
        migrations.RemoveConstraint(
            model_name='step',
            name='unique_step_order_per_module',
        ),
        migrations.RemoveConstraint(
            model_name='stepasset',
            name='unique_asset_per_step',
        ),
        migrations.AddField(
            model_name='stepasset',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='publishedmodule',
            unique_together={('module', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('module', 'order_index')},
        ),
        migrations.AlterUniqueTogether(
            name='stepasset',
            unique_together={('step', 'asset')},
        ),
    ]
