# Generated by Django 5.0.14 on 2026-02-13 06:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0005_task_alter_step_unique_together_step_task_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stepasset',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stepasset',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='stepasset',
            name='step',
        ),
        migrations.RemoveField(
            model_name='module',
            name='cover_asset',
        ),
        migrations.RemoveField(
            model_name='step',
            name='animation',
        ),
        migrations.RemoveField(
            model_name='step',
            name='body',
        ),
        migrations.RemoveField(
            model_name='step',
            name='required',
        ),
        migrations.RemoveField(
            model_name='step',
            name='ui_template',
        ),
        migrations.AddField(
            model_name='module',
            name='estimated_duration_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='module',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='module',
            name='mode',
            field=models.CharField(choices=[('VR', 'Virtual Reality'), ('AR', 'Augmented Reality')], default='VR', max_length=10),
        ),
        migrations.AddField(
            model_name='module',
            name='module_id',
            field=models.CharField(blank=True, help_text='Human-readable module identifier (e.g., PUMP_MAINT_001). Auto-generated if blank.', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='module',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='module',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail_for_modules', to='authoring.asset'),
        ),
        migrations.AddField(
            model_name='step',
            name='completion_type',
            field=models.CharField(blank=True, choices=[('button_clicked', 'Button Clicked'), ('animation_completed', 'Animation Completed'), ('interaction_completed', 'Interaction Completed'), ('time_spent', 'Time Spent'), ('user_confirmed', 'User Confirmed')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='step',
            name='completion_value',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='step',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='step',
            name='instruction_type',
            field=models.CharField(choices=[('info', 'Info'), ('safety', 'Safety'), ('observe', 'Observe'), ('action', 'Action'), ('inspect', 'Inspect'), ('completion', 'Completion'), ('question', 'Question')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='step',
            name='interaction_attempts_allowed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='step',
            name='interaction_hand',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='step',
            name='interaction_input_method',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='step',
            name='interaction_required_action',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='step',
            name='interaction_target',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='step',
            name='media_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_for_steps', to='authoring.asset'),
        ),
        migrations.AddField(
            model_name='step',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='model_animation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='step',
            name='model_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_for_steps', to='authoring.asset'),
        ),
        migrations.AddField(
            model_name='step',
            name='model_position_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='step',
            name='model_position_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='step',
            name='model_position_z',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='step',
            name='model_rotation_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='step',
            name='model_rotation_y',
            field=models.FloatField(default=180.0),
        ),
        migrations.AddField(
            model_name='step',
            name='model_rotation_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='step',
            name='model_scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='module',
            name='version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.CreateModel(
            name='StepChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('go_to_step', models.ForeignKey(blank=True, help_text='The step to jump to when this choice is selected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice_targets', to='authoring.step')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='authoring.step')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.DeleteModel(
            name='PublishedModule',
        ),
        migrations.DeleteModel(
            name='StepAsset',
        ),
    ]
