# Generated by Django 5.0.14 on 2026-02-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0006_unity_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='model_animation_loop',
            field=models.BooleanField(default=False),
        ),
    ]
