# Generated by Django 5.0.14 on 2026-02-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0007_step_model_animation_loop'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='models_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
