# Generated by Django 5.0.14 on 2026-02-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0008_step_models_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
